# Usa uma imagem base do Node.js
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos necessários
COPY package.json .
COPY package-lock.json .
COPY server.js .

# Instala as dependências
RUN npm install

#A porta do app
EXPOSE 3000

# Comando para iniciar o servidor
CMD ["node", "server.js"]
